version: 2
jobs:
  build:
    working_directory: ~/pirate
    docker:
      - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: pirate-{{ checksum "build.sbt" }}
      - run:
          name: Compile
          command: cat /dev/null | ./sbt clean compile
      - run:
          name: Test
          command: |
            ./sbt test
            ./src/test/bin/run
      - save_cache:
          key: pirate-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
